animals = ['bear', 'python', 'peacock', 'kangaroo', 'whale', 'platypus']

print "1. The animal at 1 is the 2nd animal and is a : ", animals[1]
print "2. The third (3rd) animal is at 2 and is a : ", animals[2]
print "3. The first (1st) animal is at 0 and is a : ", animals[0]
print "4. The animal at 3 is the 4th and is a : ", animals[3]
print "5. The fifth (5th) animal is at 4 and is a : ", animals[4]
print "6. The animal at 2 is the 3rd and is a : ", animals[2]
print "7. The sixth (6th) animal is at 5 and is a : ", animals[5]
print "8. The animal at 4 is the 5th and is a : ", animals[4]
